### ISSUE TITLE
feature request: log the originator of message delete events

### ISSUE THREAD

**Issue by esotericist** [caf203/loggerv3#24]
while it's very helpful to have a history of removed messages, their author, and their contents, it'd be convenient if that log also included who initiated the removal.

this would greatly reduce the amount of time squinting at audit logs to check whether a moderator was the one who removed the message, or if the user removed it themselves.

**Comment by Gideon-Foxo** [comment]
This is offered in the patron bot and isn't suitable for scale like this.

**Comment by esotericist** [comment]
somehow i missed that was a patron version feature. fair enough, i suppose.
