### ISSUE TITLE
add multi db

### ISSUE THREAD

**Issue by alphaleadership** [caf203/loggerv3#25]
quick.db

**Comment by Gideon-Foxo** [comment]
What

**Comment by alphaleadership** [comment]
add suport of quick.db node module

**Comment by SUPERCHIEFYT** [comment]
I doubt there will be support for `quick.db` - postgres is the main database that's used, on the `exe` branch it's converted to `sqlite3` but it's way outdated. 

However you could fork the repo and switch to `quick.db` in your fork.

**Comment by curtisf** [comment]
I see the appeal, but it's an enormous amount of effort to convert everything database over to quickdb and maintain it. As said above, I don't think I will have the time or ability to implement/maintain this. Maybe if anything, a future rewrite can use Knex for multi db support.
